### ISSUE TITLE
Retrieve whoami from endpoint

### ISSUE THREAD

**Issue by chrisjsewell** [eth-cscs/pyfirecrest#58]
firecrest has now added the `/utilities/whoami` endpoint: https://github.com/eth-cscs/firecrest/blob/dbf5e684baba649ad6c9f9ec57ee030ea42917ab/doc/openapi/firecrest-developers-api.yaml#L1183

meaning that this FIXME can be fixed 😄  https://github.com/eth-cscs/pyfirecrest/blob/5edbe85d11b977ed8f6943ca22e4fdc3d6f5e12d/firecrest/BasicClient.py#L965

**Comment by ekouts** [comment]
Fixed in #60.
