### ISSUE TITLE
Relax `packaging` dependency version pinning

### ISSUE THREAD

**Issue by simonbray** [eth-cscs/pyfirecrest#64]
Hi, would it be possible to relax the `packaging` dependency version pinning? I spent some time this morning updating to `pyfirecrest==0.5.1`, which seems to be needed since the recent FirecREST update on CSCS, but we unfortunately need to stick to `packaging==21.3` in our environment at the minute. After forcing pip to install the older version, everything seems to work fine. If pyfirecrest doesn't absolutely require the newer version, perhaps the pinning could be relaxed a bit? Thanks for considering. :)

Regards, Simon

**Comment by ekouts** [comment]
Hi @simonbray , thanks a lot for your input. We will also test it and if it looks okay, we will relax the version as you suggested.

**Comment by simonbray** [comment]
Thank you!
